ALLEXE = 
#CXX= g++-4.4
#CXX= g++-4.8
#CXX= clang++-3.4
#CXX= mpiCC
CXXFLAGS+=  -I${BOOST_ROOT} 
CXXFLAGS+=  -I${MTL} 
CXXFLAGS+= -Wall -pedantic
#CXXFLAGS+= -w               # no warnings at all

#CXXFLAGS+= -Wall -g -O0
CXXFLAGS+= -Wall -O3 -DNDEBUG -ffast-math
CXXFLAGS+= -funroll-loops